// Generated by tools/gen_mdi.py from MaterialDesign-Webfont 7.4.47. Do not edit.
// Add icon names to tools/gen_mdi.py and re-run it instead.
#pragma once

namespace spotty::mdi {

inline constexpr char32_t CircleOutline = 0xF0766;
inline constexpr char32_t CheckboxBlankCircle = 0xF012F;
inline constexpr char32_t AlertCircleOutline = 0xF05D6;
inline constexpr char32_t PowerPlug = 0xF06A5;
inline constexpr char32_t PowerPlugOff = 0xF06A6;
inline constexpr char32_t Refresh = 0xF0450;
inline constexpr char32_t Cog = 0xF0493;
inline constexpr char32_t TuneVariant = 0xF1542;
inline constexpr char32_t SerialPort = 0xF065C;
inline constexpr char32_t Usb = 0xF0553;
inline constexpr char32_t ConsoleLine = 0xF07B7;
inline constexpr char32_t FormatText = 0xF0284;
inline constexpr char32_t Hexadecimal = 0xF12A7;
inline constexpr char32_t Broom = 0xF00E2;
inline constexpr char32_t ArrowCollapseDown = 0xF0792;
inline constexpr char32_t Wrap = 0xF05B6;
inline constexpr char32_t WrapDisabled = 0xF0BDF;
inline constexpr char32_t ClockOutline = 0xF0150;
inline constexpr char32_t SwapHorizontal = 0xF04E1;
inline constexpr char32_t Flash = 0xF0241;
inline constexpr char32_t RecordCircleOutline = 0xF0EC3;
inline constexpr char32_t Magnify = 0xF0349;
inline constexpr char32_t ShuffleVariant = 0xF049F;
inline constexpr char32_t Play = 0xF040A;
inline constexpr char32_t Pause = 0xF03E4;
inline constexpr char32_t Stop = 0xF04DB;
inline constexpr char32_t Record = 0xF044A;
inline constexpr char32_t ContentCopy = 0xF018F;
inline constexpr char32_t ContentSave = 0xF0193;
inline constexpr char32_t Plus = 0xF0415;
inline constexpr char32_t Minus = 0xF0374;
inline constexpr char32_t Pencil = 0xF03EB;
inline constexpr char32_t Delete = 0xF01B4;
inline constexpr char32_t Close = 0xF0156;
inline constexpr char32_t Check = 0xF012C;
inline constexpr char32_t ChevronDown = 0xF0140;
inline constexpr char32_t ChevronUp = 0xF0143;
inline constexpr char32_t ChevronLeft = 0xF0141;
inline constexpr char32_t ChevronRight = 0xF0142;
inline constexpr char32_t FolderOpen = 0xF0770;
inline constexpr char32_t FileDocumentOutline = 0xF09EE;
inline constexpr char32_t OpenInNew = 0xF03CC;
inline constexpr char32_t Send = 0xF048A;
inline constexpr char32_t Keyboard = 0xF030C;
inline constexpr char32_t History = 0xF02DA;
inline constexpr char32_t Filter = 0xF0232;
inline constexpr char32_t FilterOff = 0xF14EF;
inline constexpr char32_t Palette = 0xF03D8;
inline constexpr char32_t Translate = 0xF05CA;
inline constexpr char32_t FormatFont = 0xF06D6;
inline constexpr char32_t FormatSize = 0xF027F;
inline constexpr char32_t ThemeLightDark = 0xF050E;
inline constexpr char32_t WeatherNight = 0xF0594;
inline constexpr char32_t WhiteBalanceSunny = 0xF05A8;
inline constexpr char32_t InformationOutline = 0xF02FD;
inline constexpr char32_t AlertOutline = 0xF002A;
inline constexpr char32_t TimerOutline = 0xF051B;
inline constexpr char32_t Puzzle = 0xF0431;
inline constexpr char32_t RenameBox = 0xF0455;
inline constexpr char32_t ContentDuplicate = 0xF0191;
inline constexpr char32_t FileImport = 0xF0220;
inline constexpr char32_t FileExport = 0xF021D;
inline constexpr char32_t ChartLine = 0xF012A;
inline constexpr char32_t FileUpload = 0xF0A4D;
inline constexpr char32_t FormatListNumbered = 0xF027B;

} // namespace spotty::mdi
