#!/usr/bin/env python3
"""Пересоздаёт include/spotty/ui/MdiCodepoints.h из метаданных шрифта Material Design Icons.

Spotty встраивает веб-шрифт целиком, но по имени обращается лишь к нескольким десяткам
глифов. Поэтому в репозитории лежит порождённый заголовок только с нужными константами, а
не таблица на 7000 записей.

Чтобы добавить значок: впишите его имя в стиле kebab-case в список ICONS и запустите
скрипт заново.

    python3 tools/gen_mdi.py                    # скачать метаданные
    python3 tools/gen_mdi.py _variables.scss    # либо взять локальную копию

Загрузка идёт через curl, а не urllib: интерпретатор с python.org на macOS поставляется без
пригодного набора корневых сертификатов, и urllib падает на проверке TLS.
"""

import re
import subprocess
import sys
from pathlib import Path

VARIABLES_URL = (
    "https://raw.githubusercontent.com/Templarian/"
    "MaterialDesign-Webfont/master/scss/_variables.scss"
)

#: Используемые значки. Имена — как в каталоге Material Design Icons.
ICONS = """
circle-outline checkbox-blank-circle alert-circle-outline power-plug power-plug-off
refresh cog tune-variant serial-port usb console-line format-text hexadecimal broom
arrow-collapse-down wrap wrap-disabled clock-outline swap-horizontal flash
record-circle-outline magnify shuffle-variant play pause stop record content-copy
content-save plus minus pencil delete close check chevron-down chevron-up chevron-left
chevron-right folder-open file-document-outline open-in-new send keyboard history filter
filter-off palette translate format-font format-size theme-light-dark weather-night
white-balance-sunny information-outline alert-outline timer-outline puzzle rename-box
content-duplicate file-import file-export chart-line file-upload format-list-numbered table-off
format-letter-case regex format-letter-matches image-broken-variant
chart-areaspline axis-y-arrow format-columns arrow-collapse-right monitor-screenshot camera table
chart-scatter-plot chart-bell-curve chart-bell-curve-cumulative poll chart-multiple
target-variant backup-restore sine-wave square-wave triangle-wave sawtooth-wave step-forward
""".split()

HEADER = Path(__file__).resolve().parent.parent / "include" / "spotty" / "ui" / "MdiCodepoints.h"


def pascal(name: str) -> str:
    """Преобразует `arrow-collapse-down` в `ArrowCollapseDown`."""
    return "".join(part.capitalize() for part in name.split("-"))


def fetch() -> str:
    """Возвращает содержимое _variables.scss — из файла в аргументах либо из сети."""
    if len(sys.argv) > 1:
        return Path(sys.argv[1]).read_text(encoding="utf-8")
    result = subprocess.run(
        ["curl", "-sSfL", VARIABLES_URL], capture_output=True, text=True, check=True
    )
    return result.stdout


def main() -> int:
    scss = fetch()

    version_match = re.search(r'\$mdi-version:\s*"([^"]+)"', scss)
    version = version_match.group(1) if version_match else "unknown"

    # Строки файла имеют вид:  "abacus": F16E0,
    codepoints = {}
    for match in re.finditer(r'^\s*"([a-z0-9-]+)":\s*([0-9A-F]+),?', scss, re.MULTILINE):
        if match.group(1) in ICONS:
            codepoints[match.group(1)] = match.group(2)

    # Опечатка в имени значка иначе тихо дала бы отсутствующую константу и ошибку сборки
    # в совершенно другом файле.
    missing = [name for name in ICONS if name not in codepoints]
    if missing:
        print(f"error: unknown MDI icon names: {', '.join(missing)}", file=sys.stderr)
        return 1

    lines = [
        f"// Generated by tools/gen_mdi.py from MaterialDesign-Webfont {version}. Do not edit.",
        "// Add icon names to tools/gen_mdi.py and re-run it instead.",
        "#pragma once",
        "",
        "namespace spotty::mdi {",
        "",
    ]
    lines += [f"inline constexpr char32_t {pascal(n)} = 0x{codepoints[n]};" for n in ICONS]
    lines += ["", "} // namespace spotty::mdi", ""]

    HEADER.write_text("\n".join(lines))
    print(f"wrote {len(ICONS)} icons to {HEADER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
